// Code generated by "stringer -type=MainCollectionType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MainCollectionTypePhysical-0]
	_ = x[MainCollectionTypeApplication-1]
	_ = x[MainCollectionTypeLogical-2]
	_ = x[MainCollectionTypeReport-3]
	_ = x[MainCollectionTypeNamedArray-4]
	_ = x[MainCollectionTypeUsageSwitch-5]
	_ = x[MainCollectionTypeUsageModifier-6]
}

const _MainCollectionType_name = "MainCollectionTypePhysicalMainCollectionTypeApplicationMainCollectionTypeLogicalMainCollectionTypeReportMainCollectionTypeNamedArrayMainCollectionTypeUsageSwitchMainCollectionTypeUsageModifier"

var _MainCollectionType_index = [...]uint8{0, 26, 55, 80, 104, 132, 161, 192}

func (i MainCollectionType) String() string {
	if i >= MainCollectionType(len(_MainCollectionType_index)-1) {
		return "MainCollectionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MainCollectionType_name[_MainCollectionType_index[i]:_MainCollectionType_index[i+1]]
}
